import {assert,redact,LIMITS} from './utils.mjs';
const PHONE=/\b1[3-9]\d{9}\b/g, VIN=/\b[A-HJ-NPR-Z0-9]{17}\b/gi, ID=/\b\d{17}[0-9Xx]\b/g, EMAIL=/[\w.+-]+@[\w.-]+\.[a-z]{2,}/gi, URL=/https?:\/\/[^\s"'<>]+/gi, COORD=/-?\d{1,3}\.\d{3,}\s*[,，]\s*-?\d{1,3}\.\d{3,}/g;
const count=(re,s)=>[...s.matchAll(re)].length;
export function scanSensitive(files){let all=files.map(f=>f.content).join('\n'),out=[];const add=(id,title,severity,category,n,evidence,suggestion)=>{if(n)out.push({id,indicator:id,category,title,severity,confidence:'high',count:n,evidence:redact(evidence),suggestion,source_files:files.map(f=>f.name)})};
add('P001','发现明文手机号','High','privacy',count(PHONE,all),[...all.matchAll(PHONE)].slice(0,3).map(x=>x[0]).join(', '),'对日志和导出文件中的手机号脱敏，核查访问权限。');
add('P002','发现明文 VIN','Medium','privacy',count(VIN,all),[...all.matchAll(VIN)].slice(0,3).map(x=>x[0]).join(', '),'核查 VIN 与个人的关联可能，减少日志记录并去标识化。');
add('P003','发现明文邮箱','Medium','privacy',count(EMAIL,all),[...all.matchAll(EMAIL)].slice(0,3).map(x=>x[0]).join(', '),'按用途最小化记录邮箱，并实施脱敏及访问控制。');
add('P004','发现疑似明文身份证号','High','privacy',count(ID,all),[...all.matchAll(ID)].slice(0,2).map(x=>x[0]).join(', '),'核实匹配值并停止非必要明文记录。');
add('P005','发现精确位置数据','High','privacy',count(COORD,all),[...all.matchAll(COORD)].slice(0,2).map(x=>x[0]).join(', '),'确认位置数据必要性、存储加密、密钥管理和访问控制。');
add('T001','发现 HTTP 明文 URL','High','transport',count(URL,all),[...all.matchAll(URL)].slice(0,3).map(x=>x[0]).join(', '),'核验真实传输链路并使用 TLS，检查证书及协议配置。');
if(/(?:encrypted|加密)\s*["']?\s*[:=]\s*(?:false|0|no|否)/i.test(all))add('P005','数据对象标记为未加密','High','privacy',1,'encrypted=false','确认位置等敏感数据的存储加密、密钥管理和访问控制。');return out}
export function scanCan(files){let out=[];for(const f of files){if(!/\.(csv|log|txt)$/i.test(f.name))continue;const lines=f.content.split(/\r?\n/).filter(Boolean).slice(0,LIMITS.rows);let rows=0,bad=0,prev=null,ids=new Map(),first=null;for(const line of lines){if(/timestamp|can.?id|dlc/i.test(line)&&rows===0)continue;const p=line.includes(',')?line.split(',').map(x=>x.trim()):line.trim().split(/\s+/);if(p.length<3){bad++;continue}const ts=Number(p[0]),id=String(p[1]).replace(/^0x/i,'').toUpperCase(),dlc=Number(p[2]);if(!Number.isFinite(ts)||!Number.isFinite(dlc)||dlc<0||dlc>8){bad++;continue}if(first===null)first=ts;rows++;ids.set(id,(ids.get(id)||0)+1);if(prev!==null&&ts<prev)bad++;prev=ts}if(!rows){if(bad)out.push({id:'C003',indicator:'C003',category:'can',title:'CAN 文件无法按预期解析',severity:'Medium',confidence:'low',count:bad,evidence:'未解析到有效的时间戳、CAN ID、DLC 行',suggestion:'按公开数据集格式提供 Timestamp、CAN ID、DLC、Payload；不要将 Flag 作为检测输入。',source_files:[f.name]});continue}const max=[...ids.entries()].sort((a,b)=>b[1]-a[1])[0],duration=Math.max(0,(prev??first)-first),rate=duration>0?max[1]/duration:0;if(rate>1000)out.push({id:'C001',indicator:'C001',category:'can',title:'发现 CAN ID 高频异常线索',severity:'High',confidence:'medium',count:max[1],evidence:'文件 '+f.name+' 中 CAN ID '+max[0]+' 约 '+rate.toFixed(1)+' 条/秒',suggestion:'复核时间单位及正常基线，调查高频原因；不得仅凭高频认定攻击类型。',source_files:[f.name]});if(bad)out.push({id:'C003',indicator:'C003',category:'can',title:'发现 CAN 数据质量问题',severity:'Medium',confidence:'high',count:bad,evidence:bad+' 行格式异常或时间戳逆序',suggestion:'检查时间戳、DLC 和数据字节，异常格式应先修复再分析。',source_files:[f.name]});if(max&&max[1]>0&&ids.size<3)out.push({id:'C002',indicator:'C002',category:'can',title:'CAN 标识符覆盖较少，需核验基线',severity:'Medium',confidence:'low',count:ids.size,evidence:'仅发现 '+ids.size+' 个 CAN ID；未知标识符不能直接判定为恶意',suggestion:'核查 DBC 和基线覆盖范围，判断新 CAN ID 是否属于合法功能。',source_files:[f.name]})}return out}
export function runDetectors(files){assert(files.length,'没有可检测文件');return [...scanSensitive(files),...scanCan(files)]}